"use client";

import { useEffect } from "react";

/**
 * Registers /sw.js (generated by src/app/sw.js/route.ts) once the app has
 * loaded in the browser. Renders nothing — this is a side-effect-only
 * component, kept separate from LocaleProvider/page.tsx so it's obvious at
 * a glance in layout.tsx what it's for.
 *
 * Real user report (2026-09-16): an installed ("Add to Home Screen") copy
 * of the app never picked up new deploys. Root cause, per the Service
 * Worker spec's own update algorithm: the browser only re-checks sw.js for
 * a new version on a full navigation to a page in scope -- but a
 * standalone-installed PWA is usually just RESUMED from the background,
 * not freshly navigated to, so that check rarely fired in practice. And
 * even when a new worker DID activate in the background (self.skipWaiting()
 * + self.clients.claim() in sw.js already made it take control of open
 * clients), nothing told the already-loaded page to reload -- its JS just
 * kept running from memory. Two additions close both gaps:
 * - `registration.update()` on visibilitychange -- the exact moment an
 *   installed app is "relaunched" from the background, so this is the
 *   natural place to force the check the browser wasn't doing on its own.
 * - a `controllerchange` listener that reloads the page once a new worker
 *   takes control, so the update actually reaches what's on screen instead
 *   of only taking effect on some future, unrelated reload.
 */
export default function ServiceWorkerRegister() {
  useEffect(() => {
    if (!("serviceWorker" in navigator)) return;

    let registration: ServiceWorkerRegistration | undefined;
    // Guards against a reload loop -- controllerchange can in principle
    // fire more than once (e.g. an old worker still finishing up), but this
    // app only ever wants to react to the first one.
    let reloaded = false;

    navigator.serviceWorker
      .register("/sw.js")
      .then((r) => {
        registration = r;
      })
      .catch(() => {
        // Non-fatal — the app works fully online without it, this only
        // loses the offline/installed-app benefits.
      });

    function checkForUpdate() {
      if (document.visibilityState === "visible") registration?.update().catch(() => {});
    }
    document.addEventListener("visibilitychange", checkForUpdate);

    function onControllerChange() {
      if (reloaded) return;
      reloaded = true;
      window.location.reload();
    }
    navigator.serviceWorker.addEventListener("controllerchange", onControllerChange);

    return () => {
      document.removeEventListener("visibilitychange", checkForUpdate);
      navigator.serviceWorker.removeEventListener("controllerchange", onControllerChange);
    };
  }, []);

  return null;
}
